- Effect: Allow
  Action:
    - "dynamodb:PutItem"
    - "dynamodb:GetItem"
    - "dynamodb:UpdateItem"
    - "dynamodb:DeleteItem"
    - "dynamodb:BatchGetItem"
    - "dynamodb:BatchWriteItem"
    - "dynamodb:Query"
  Resource: "*"
